language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit

php:
    - 7.2

script:
    - ./vendor/bin/simple-phpunit --coverage-text --colors