language: php
php:
- '7.4'
script:
- composer install
- vendor/bin/simple-phpunit
deploy:
  api_key:
    secure: fR1gqxXlnznUX1fqSMa4wRKmBFtTx9rMN8EaN9ABToBEaF9X/ApNIg94EJmw6DYM7+r/LnSRBYgyYyoXd3eAK9bSTrxB8098qRx6va2aRiFJUHeah62f7w04KlP206MDWJ/DwCLHZecz/wdmguQ1VkW/Vv2ciBVgPfEyR6tmPIx1Y3VG+lzQlcDphWVgOFmRT4ksan7OJ5CaVUH5mh7Q3EpEorMjzGrgN51Ul9kHX9KQfNCOKeBngoy/MUVlXJHS7JLTAZlPQ5cwBj6kzIEqgeckkBOJz6XVXZFvL13pZAN8+ZQrYhyAp7a58E1V41YLoaGx+JZoDw371T/tIeuHQWYIT7NehSvcLryaBWhRZPkjOGwSl2P/KDvZqakvHYDp513P9oDTksB40t+2gBk5IZwYlMTkNEysnOimEYZ7j7e/9WqDhDxAQwpin8XCIx7l8ioyCmZm3WhvjbEy/D8U4YteGxpBDB91FwD/nGwFxvQzq8SeFlMyRCpVFtKrR9dl60PR/6WiNlD2ZvXl3w7XqGxm3yS6kXnCy03Q1d0Ecfg/q9dvTwhXqcQ7yCQ+l0UvbeVI1QWmj0LX6EmYvV0pTiIaeyNuIedYnGmHzbGw3UQ71EoyANnEJNHM2ri482agXiiptiEeV5hOKdaLPhFEjwTLxgSPGlpNLD4bq6cYKwc=
  on: dev